start-at-login = true

after-login-command = []

after-startup-command = [
  'exec-and-forget borders active_color=0xfffff11f inactive_color=0x00000000 width=8.0',
]

enable-normalization-flatten-containers = true

enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 8
    inner.vertical = 8
    outer.left = 8
    outer.bottom = 8
    outer.top = 8
    outer.right = 8

[mode.main.binding]
    #######################################
    # APP HOTKEYS
    #######################################
    cmd-shift-t = '''exec-and-forget env KITTY_WINDOW_ID=new-instance open -na "kitty"'''
    cmd-t = '''exec-and-forget open -a "kitty"'''
    cmd-b = '''exec-and-forget open -a "Brave Browser"'''
    cmd-e = '''exec-and-forget open -a "Finder"'''

    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # focus windows
    cmd-h = 'focus left --boundaries all-monitors-outer-frame'
    cmd-j = 'focus down --boundaries all-monitors-outer-frame'
    cmd-k = 'focus up --boundaries all-monitors-outer-frame'
    cmd-l = 'focus right --boundaries all-monitors-outer-frame'

    # move to workspace
    cmd-1 = ['workspace 1']
    cmd-2 = ['workspace 2']
    cmd-3 = ['workspace 3']
    cmd-4 = ['workspace 4']
    cmd-5 = ['workspace 5']
    cmd-6 = ['workspace 6']
    cmd-7 = ['workspace 7']
    cmd-8 = ['workspace 8']
    cmd-9 = ['workspace 9']
    cmd-0 = ['workspace 10']
    cmd-ctrl-h = ['workspace prev']
    cmd-ctrl-l = ['workspace next']
    cmd-alt-h = ['move-node-to-workspace prev --focus-follows-window']
    cmd-alt-l = ['move-node-to-workspace next --focus-follows-window']

    # move to monitor
    cmd-o = 'move-node-to-monitor next --focus-follows-window --wrap-around'
    cmd-i = 'move-node-to-monitor prev --focus-follows-window --wrap-around'
    cmd-shift-i = 'move left'
    cmd-shift-o = 'move right'

    cmd-shift-minus = 'resize smart -50'
    cmd-shift-equal = 'resize smart +50'

    cmd-shift-enter = 'mode service'

[mode.service.binding]
    1 = 'move-node-to-workspace --focus-follows-window 1'
    2 = 'move-node-to-workspace --focus-follows-window 2'
    3 = 'move-node-to-workspace --focus-follows-window 3'
    4 = 'move-node-to-workspace --focus-follows-window 4'
    5 = 'move-node-to-workspace --focus-follows-window 5'
    6 = 'move-node-to-workspace --focus-follows-window 6'
    7 = 'move-node-to-workspace --focus-follows-window 7'
    8 = 'move-node-to-workspace --focus-follows-window 8'
    9 = 'move-node-to-workspace --focus-follows-window 9'
    0 = 'move-node-to-workspace --focus-follows-window 10'

    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']


#####################################################
# MONITOR-WORKSPACE ASSIGNMENT
#####################################################
[workspace-to-monitor-force-assignment]
    1 = [1]     # browser
    2 = [1]     # mail, calendar
    3 = [2, 1]  # shell
    4 = [2, 1]
    5 = [3, 1]  # spotify
    6 = [3, 1]
    7 = [3, 1]
    8 = [3, 1]  # notion
    9 = [3, 1]  # linear
    0 = [3, 1]  # slack

#####################################################
# AUTO APP TO WORKSPACE
#####################################################
[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['layout tiling', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['layout tiling', 'move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'notion.id'
run = ['layout tiling', 'move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'com.linear'
run = ['layout tiling', 'move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout tiling', 'move-node-to-workspace 10']

